[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.\n
"""
body = """
{% if version %}\
    # [{{ version|trim_start_matches(pat="v") }}]\
    {% if previous %}\
        {% if previous.version %}\
            (https://github.com/pixelpizza/ts-monorepo-template/compare/{{ previous.version }}...{{ version }})\
        {% else %}\
            (https://github.com/pixelpizza/ts-monorepo-template/tree/{{ version }})\
        {% endif %}\
    {% endif %}\
    - ({{ timestamp|date(format="%Y-%m-%d") }})
{% else %}\
    # [unreleased]
{% endif %}\
{% for group, commits in commits|group_by(attribute="group") %}
    ## {{ group|upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}\
            **{{ commit.scope }}:**\
          {% endif %}\
        {{ commit.message|upper_first }} ([{{ commit.id|truncate(length=7, end="") }}](https://github.com/pixelpizza/ts-monorepo-template/commit/{{ commit.id }}))\
        {% if commit.breaking %}
            {% for breakingChange in commit.footers %}\
                \n{% raw %}  {% endraw %}- **BREAKING CHANGE:** **{{ breakingChange.token }}{{ breakingChange.separator }}** {{ breakingChange.value }}\
            {% endfor %}\
        {% endif %}\
    {% endfor %}
{% endfor %}\n
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^docs", group = "Documentation" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactor" },
    { message = "^revert", skip = true },
    { message = "^style", group = "Styling" },
    { message = "^test", group = "Testing" },
    { message = "^chore", skip = true },
    { message = "^ci", skip = true },
    { message = "^build", skip = true },
    { message = ".*deprecated", body = ".*deprecated", group = "Deprecations" },
    { body = ".*security", group = "Security" }
]
filter_commits = true
tag_pattern = "@jaronline/example@[0-9]*"
ignore_tags = ""
topo_order = false
sort_commits = "newest"
